version: '2.4'

services:
  app: &app
    build:
      context: .dockerdev
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: '2.7.2'
        PG_MAJOR: '11'
        BUNDLER_VERSION: '2.1.4'
    image: loyalty-area-dev:1.0.0
    tmpfs:
      - /tmp

  backend: &backend
    <<: *app
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/usr/local/bundle
      - .dockerdev/.psqlrc:/root/.psqlrc:ro
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - REDIS_URL=redis://redis:6379/
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432
      - BOOTSNAP_CACHE_DIR=/usr/local/bundle/_bootsnap
      - WEB_CONCURRENCY=1
      - HISTFILE=/app/log/.bash_history
      - PSQL_HISTFILE=/app/log/.psql_history
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  rails:
    <<: *backend
    container_name: loyalty_area_rails
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - '3000:3000'

  sidekiq:
    <<: *backend
    container_name: loyalty_area_sidekiq
    command: bundle exec sidekiq -C config/sidekiq.yml

  auth:
    container_name: loyalty_area_auth
    image: tiny_goauth_dev
    ports: ['8080:8080']
    environment:
      REDIS_URL: redis://redis:6379/
      DB_URL: postgres://postgres:postgres@postgres:5432

      APP_HOST: 127.0.0.1
      APP_PORT: 8080

      ACCESS_PRIVATE_PATH: /app/keys/access_private.rsa
      REFRESH_PRIVATE_PATH: /app/keys/refresh_private.rsa

      ACCESS_PUBLIC_PATH: /app/keys/access_public.rsa.pub
      REFRESH_PUBLIC_PATH: /app/keys/refresh_public.rsa.pub

      API_HOST: http://rails
    volumes:
      - ./config/keys:/app/keys
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:11.1
    container_name: loyalty_area_db
    volumes:
      - .psqlrc:/root/.psqlrc:ro
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      - PSQL_HISTFILE=/root/log/.psql_history
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  redis:
    image: redis:3.2-alpine
    container_name: loyalty_area_redis
    volumes:
      - redis:/data
    ports:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  postgres:
    name: loyalty-area-pg
  redis:
    name: loyalty-area-redis
  bundle:
    name: loyalty-area-bundle
  rails_cache:
    name: loyalty-area-cache
