default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch( 'RAILS_MAX_THREADS' ){ 5 } %>
  host:  <%= ENV.fetch( 'DB_HOST' ){ 'db' } %>
  port: <%= ENV.fetch( 'DB_PORT' ){ 5432 } %>
  username: <%= ENV.fetch 'DB_USER' %>
  password: <%= ENV.fetch 'DB_PASSWORD' %>

development:
  <<: *default
  database: <%= ENV.fetch( 'DB_NAME' ){ 'loyalty_area_development' } %>

test:
  <<: *default
  database: loyalty_area_test

production:
  <<: *default
  database: <%= ENV.fetch 'DB_NAME' %>
